spring:
  main:
    banner-mode: LOG
#  servlet:
#    multipart:
#      max-file-size: 128KB
#      max-request-size: 128KB
#  resources:
#    static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/templates/
  jms:
    listener:
      receive-timeout: 30000 # resets the initial timeout value to 30 seconds which has been shown to be more cost-effective.
      concurrency: 1
      max-concurrency: 5
    template:
      default-destination: DEV.QUEUE.1
      receive-timeout: 30000
    cache:
      enabled: true
      consumers: true
      producers: true
      session-cache-size: 1

ibm:
  mq:
    clientId: CID-Java-App
    applicationName: MQApp
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd
    # ccdtUrl: file:///D:\\WORKSPACE\\FIL_WORKSPACE\\ibmmq\\AMQCLCHL.TAB
    # sslCipherSpec:     # Cipher Spec, sets connectionFactory property WMQConstants.WMQ_SSL_CIPHER_SPEC
#    additional-properties:


demo:
  storage:
    location: D:\\WORKSPACE\\FIL-WORKSPACE\\logs\\upload
  queue:
    local2: DEV.QUEUE.2
    local3: DEV.QUEUE.3
  file:
    default: archive/msg.in
    output: D:\\WORKSPACE\\FIL-WORKSPACE\\logs\\msg.out
logging:
  file:
    name: D:\\WORKSPACE\\FIL-WORKSPACE\\logs\\DemoMQ.log
