spring:
  main:
    banner-mode: LOG
#  servlet:
#    multipart:
#      max-file-size: 128KB
#      max-request-size: 128KB
#  resources:
#    static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/templates/
  jms:
    listener:
      receive-timeout: 30000 # resets the initial timeout value to 30 seconds which has been shown to be more cost-effective.
      concurrency: 1
      max-concurrency: 5
    template:
      default-destination: DEV.QUEUE.1
      receive-timeout: 30000
    cache:
      enabled: true
      consumers: true
      producers: true
      session-cache-size: 1

ibm:
  mq:
    clientId: ClientWeb
    applicationName: DemoMQ
    queueManager: QM1
    user: admin
    password: passw0rd
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    # ccdtUrl: file:///D:\\WORKSPACE\\FIL_WORKSPACE\\ibmmq\\AMQCLCHL.TAB
#    sslCipherSuite: TLS_RSA_WITH_AES_256_CBC_SHA256
#    useIBMCipherMappings: false
    # additional-properties:

demo:
  mq:
    applicationName: Monitor
    queueManager: QM1
    user: admin
    password: passw0rd
    channel: DEV.ADMIN.SVRCONN
    hostname: localhost
    port: 1414
    ccdtUrl: file:///D:\\WORKSPACE\\FIL_WORKSPACE\\ibmmq\\AMQCLCHL.TAB
    sslCipherSuite: TLS_RSA_WITH_AES_256_CBC_SHA256
  queue:
    local1: DEV.QUEUE.1
    local2: DEV.QUEUE.2
    local3: DEV.QUEUE.3
  file:
    default: archive/msg.in
    output: logs/msg.out
  storage:
    location: logs/upload
logging:
  file:
    name: logs/DemoMQ.log
